#!/usr/bin/env bash
# poorman: a process control system written in shell, for development.
#
# Copyright (c) 2013-2019, Ron DuPlain <ron.duplain@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Exit immediately if a command error or non-zero return occurs.
set -e
set -o pipefail

# Environment variables during poorman's run time.
declare POORMAN            # filepath for this instance of poorman
declare POORMAN_NAME       # name of command as listed in Procfile
declare POORMAN_COMMAND    # command-line as listed in Procfile
declare POORMAN_PAD        # space-filled string to line up stdout logging
declare POORMAN_LOG_PREFIX # pre-computed log prefix
declare POORMAN_LOG_COLOR  # ANSI escape sequence for color of current log

declare POORMAN_PID        # PID of start poorman process from `poorman start`
declare POORMAN_LOGGER_PID # PID of logger poorman process in `poorman exec`
declare -a POORMAN_PIDS    # array of PIDs of poorman-spawned processes

# When this is not-empty, poorman will kill only poorman-spawned processes.
# This is specifically useful when poorman's caller is in the same process group.
export POORMAN_SELECTIVE_KILL=${POORMAN_SELECTIVE_KILL:-}

export PROGRAM=${0##*/} # same as basename
export POORMAN=$0

# Program count, incremented by 1 on each exec. (Used in rotating colors.)
PROGRAM_COUNT=0

# Posted: endangered backslashes are protected in mountainous regions.

# Begin main functions.

main() {
    # User-facing entry point for poorman.

    if [ $# -eq 0 ]; then
        # No arguments given.
        usage
    fi

    local command=$1
    shift

    if [ "$command" = "start" ]; then
        export POORMAN_PID=$$
        trap_during_setup
        main_start "$@"
    elif [ "$command" = "exec" ]; then
        trap_during_setup
        main_exec "$@"
    elif [ "$command" = "run" ]; then
        trap_during_setup
        main_run "$@"
    elif [ "$command" = "export" ]; then
        main_export "$@"
    elif [ "$command" = "check" ]; then
        main_check "$@"
    elif [ "$command" = "source" ]; then
        # Other bash programs can source this file:
        #
        #     . path/to/poorman source
        #
        # Or if poorman is in the $PATH:
        #
        #     . poorman source
        #
        # Calling the `source` subcommand prevents normal execution.
        # In particular, this is useful in calling poorman functions.
        unset POORMAN PROGRAM # These are incorrect when poorman is sourced.
        pass
    else
        echo "error: no such command: $command" >&2
        echo >&2
        usage
    fi
}

trap_during_setup() {
    # Set trap intended for poorman during initialization.

    [[ -n "$POORMAN_SELECTIVE_KILL" ]] || trap 'clear_traps; kill 0' SIGINT SIGTERM EXIT
}

clear_traps() {
    # Call all traps known to be set by poorman.

    trap - SIGINT SIGTERM EXIT
}

main_start() {
    # Load Procfile & execute each command found, after pruning out comments.

    if [ ! -e Procfile ]; then
        echo "error: Procfile does not exist" >&2
        echo >&2
        usage
    fi

    source_dotenv

    if [ $# -eq 0 ]; then
        main_start_all
    else
        main_start_one "$@"
    fi
}

main_start_all() {
    # Start all processes in Procfile, to be called from main_start.

    # Load the Procfile, parse it, and execute the commands found there.
    build_logging_pad
    map_lines exec_procfile_line < Procfile

    # Clean up environment in case anything wants to use it.
    export POORMAN_NAME=$PROGRAM
    unset POORMAN_COMMAND

    # Set trap in a single line to simplify coverage.
    [[ -n "$POORMAN_SELECTIVE_KILL" ]] && trap 'clear_traps; kill ${POORMAN_PIDS[@]} >/dev/null 2>&1' SIGINT SIGTERM EXIT || trap 'clear_traps; kill 0' SIGINT SIGTERM EXIT

    wait
}

main_start_one() {
    # Start one process in Procfile, by name, to be called from main_start.

    if [ $# -ne 1 ]; then
        echo "error: too many names given: $@" >&2
        echo >&2
        usage
    fi

    local name="$1"
    declare command

    map_lines parse_command_for "$name" command < Procfile

    if [ -z "$command" ]; then
        echo "error: no command found for '$name'" >&2
        return 2
    fi

    eval set -- "$command"
    exec "$@"
}

main_exec() {
    # Execute given command, logging each line w/metadata prefix.

    # Disable pathname expansion to avoid glob expansion in logs.
    set -f

    # Compute the logging prefix to line up stdout among processes.
    local pad_length=${#POORMAN_PAD}
    local name_length=${#POORMAN_NAME}
    let filler_length=pad_length-name_length+1
    local log_prefix="$POORMAN_NAME${POORMAN_PAD:0:$filler_length}|"

    # Execute the command, logging each line with timestamp & program name.
    export POORMAN_LOG_PREFIX="$log_prefix"
    exec "$@" 2>&1 | map_lines log_line &
    export POORMAN_LOGGER_PID=$!

    # Set trap in a single line to simplify coverage.
    export NEXT_OF_KIN="$POORMAN_PID $POORMAN_LOGGER_PID"
    [[ -n "$POORMAN_SELECTIVE_KILL" ]] && trap 'clear_traps; kill $NEXT_OF_KIN >/dev/null 2>&1' SIGINT SIGTERM EXIT || trap 'clear_traps; kill 0' SIGINT SIGTERM EXIT

    wait
}

main_run() {
    # Load .env & execute given command, without any additional log handling.

    source_dotenv
    exec "$@"
}

main_export() {
    # Refer to reference implementation of export subcommand.

    echo "$PROGRAM: export not implemented; use foreman export." >&2
    return 2
}

main_check() {
    # Refer to reference implementation of check subcommand.

    echo "$PROGRAM: check not implemented; use foreman check." >&2
    return 2
}

add_pid() {
    # Add given pid to POORMAN_PIDS, should only be called from main process.

    local pid=$1
    shift

    local index=${#POORMAN_PIDS[@]}
    POORMAN_PIDS[$index]=$pid
}

# Begin per-line utilities, called with each line of file or output.

log_line() {
    # Log given line to stdout, prefixed with timestamp & program name.

    colored="$POORMAN_LOG_COLOR$(date +"%H:%M:%S") $POORMAN_LOG_PREFIX\033[0m"
    echo -e "$colored" "${*//\\/\\\\}" # <--- Look, mountains! ---
}

echo_env_export() {
    # Print eval-able line, intended for use with .env lines.

    local line="$@"
    local line_before_hash=${line%%\#*}
    if [[ "$line_before_hash" == *=* ]]; then
        # Line has '=' before '#'. Send it along.
        echo "export ${line//\\/\\\\}" # <--- Look, mountains! ---
    fi
}

exec_procfile_line() {
    # Parse & exec Procfile-style line, intended for use with Procfile lines.
    #
    # Calls poorman recursively to `exec` into command & support killing group.

    parse_procfile_line POORMAN_NAME POORMAN_COMMAND "$@"
    if [ -z "$POORMAN_COMMAND" ]; then
        return
    fi
    eval set -- "$POORMAN_COMMAND"

    export POORMAN_LOG_COLOR=$(pick_color $PROGRAM_COUNT)
    let PROGRAM_COUNT=PROGRAM_COUNT+1
    $POORMAN exec "$@" 2>/dev/null &
    add_pid $!
}

echo_procfile_name() {
    # Parse Procfile-style line, print name of program entry.

    parse_procfile_line name _ "$@"
    if [ -z "$name" ]; then
        return
    fi
    echo "$name"
}

parse_procfile_line() {
    # Parse Procfile-style line into arguments given by name: name, command.
    #
    # `name` is just a string.
    # `command` is raw and ready for evaluation by the shell:
    #
    #     parse_procfile_line NAME COMMAND "$procfile_line"
    #     eval set -- "$COMMAND"
    #     exec "$@"
    #
    # Use of eval here allows .env variables to be used in Procfile commands.

    # Understanding poorman internals:
    #
    # poorman reads each line from the Procfile as a simple, unprocessed string
    # (via map_lines), which puts the entire Procfile line into argument `$3`
    # when this function is called.
    #
    # At some point, poorman needs to parse the line from the Procfile exactly
    # as the shell would parse it. The best parser for this is the shell itself
    # (e.g. `set -- "$COMMAND"`), but caution must be taken in order to avoid
    # implicitly processing the string. Echoing the string will lose quoting
    # and escapes. Parsing the string into an argument array here will hit
    # limitations in what can be exported, since the name of the command
    # variable is taken as an argument. Therefore, this function passes the
    # command as a single opaque string, to be parsed via `set` just before
    # `exec` is to be called by poorman.
    #
    # Further, to be complete, poorman must support backslash escapes. The bash
    # builtin `read` parses differently from `set`, so is not an option given
    # that poorman's design intends to use `set`, as just discussed. Escaping
    # backslashes ("mountains") will ensure that `eval set -- "$COMMAND"` has
    # the correct level of escaping when parsing, with one exception:
    # spaces. '\ ' is special in that its primary intent is to indicate a space
    # in an unquoted word, typically a filepath. As such, backslash-escaped
    # spaces are intended for the shell parser (i.e. `set`) and are the
    # exception in backslash-escaped backslashes (i.e. the "valley" in the
    # "mountains").

    local name_var=$1
    local command_var=$2
    shift 2

    local line="$@"

    if [[ "$line" =~ ^[[:space:]]*# ]]; then
        # Line is comment only. Ensure values are unset for caller inspection.
        unset $name_var $command_var
        return
    fi

    line="${line//\\/\\\\}"    # <--- Look, mountains! ---
    line="${line//\\\\ /\\ }"  # <--- Look, valley! ---

    export $name_var="${line%%:*}"    # everything up to first ':'
    export $command_var="${line#*: }" # everything after first ':'
}

parse_command_for() {
    # Given a name and a Procfile-style line, print command if name matches.

    local name_var=$1
    local command_var=$2
    shift 2

    declare _parse_command_for_name _parse_command_for_command
    parse_procfile_line _parse_command_for_name _parse_command_for_command "$@"

    if [ "$_parse_command_for_name" = "$name_var" ]; then
        export $command_var="$_parse_command_for_command"
    fi
}

# Begin map utility to process lines in text using manageable functions.

map_lines() {
    # Execute given command-line for each line in stdin.

    # Understanding read & internal field separator (IFS) in bash:
    #
    # The `read` builtin reads one line of stdin and assigns words to given
    # names. Setting the internal field separator (IFS) to an empty value
    # prevents `read` from trimming whitespace from the line. Using `read -r`
    # considers a backslash as part of the input line and not an escape. Per
    # POSIX, `read` exits non-zero if an end-of-file occurs, which would happen
    # if input ends with a line that does not end with a newline, in which case
    # bash still assigns the value to the given name when exiting non-zero.

    local line_command="$@"
    shift

    if [ -z "$line_command" ]; then
        echo 'error: no command given to map_lines' >&2
        echo 'usage: map_lines COMMAND' >&2
        return 2
    fi

    while IFS= read -r line || [ -n "$line" ]; do
        $line_command "$line"
        local result=$?
        if [ $result -ne 0 ]; then
            # Ensure errors do not get swallowed in this loop.
            return $result
        fi
    done
}

# Begin top-level program utilities.

source_dotenv() {
    # Source the .env file in the current working directory, if it exists.

    local dotenv="${1:-.env}"

    if [ -e "$dotenv" ]; then
        eval "$(map_lines echo_env_export < "$dotenv")"
    fi
}

build_logging_pad() {
    # Inspect all Procfile names & set POORMAN_PAD accordingly.

    unset POORMAN_PAD

    # Find the maximum length name in the Procfile.
    local length=0
    for name in $(map_lines echo_procfile_name < Procfile); do
        if [ ${#name} -gt $length ]; then
            length=${#name}
        fi
    done

    # Space-fill the pad using that length.
    POORMAN_PAD=""
    while [ ${#POORMAN_PAD} -lt $length ]; do
        POORMAN_PAD="$POORMAN_PAD "
    done
    export POORMAN_PAD
}

# ANSI color codes to use when logging to the terminal, in rotation.
#       cyan    yellow  green   magenta red     blue
COLORS=(36      33      32      35      31      34)

pick_color() {
    # Pick a color from a preset given an integer, echo ANSI escape sequence.

    if [ $# -eq 0 ]; then
        return
    fi

    local number=$1
    shift

    let number_of_colors=${#COLORS[@]}

    let index=$number%$number_of_colors
    echo '\033['${COLORS[$index]}m
}

pass() {
    # No operation.

    :
}

usage() {
    # Print poorman program usage to stderr & return 2.

    clear_traps

    echo "usage: $PROGRAM start [PROCESS]        # Start processes." >&2
    echo "usage: $PROGRAM run COMMAND [ARGS...]  # Run arbitrary command." >&2
    echo >&2
    echo "$PROGRAM is a shell port of foreman." >&2
    echo "It reads Procfile & .env files in the current working directory." >&2
    return 2
}

main "$@"
