#!/usr/bin/env bash
# tick: echo . .. ..., wait indefinitely unless --exit given; change . with $DOT.

dot=${DOT:-.}

echo $dot
echo $dot$dot
echo $dot$dot$dot

if [ "$1" = "--exit" ]; then
    sleep 0.1
    exit
else
    sleep 2
fi
